### ISSUE TITLE
Have the list of participants easily accessible in the API

### ISSUE THREAD

**Issue by sandhose** [MichaelMure/git-bug#107]
I'd like to add the list of participants in the webui, like in gitea:

![image](https://user-images.githubusercontent.com/1549952/55111837-8cb14b00-50db-11e9-844f-814d6cbfd26b.png)

For that, I need the list of people that interacted with the bug in the GraphQL API. Because it implies to go through the whole list of operations to lists authors, this might be something we want to have in the cache.

**Comment by MichaelMure** [comment]
Good point !

We don't necessarely need to have the list of participants in the cache, because we load the full bug from git anyway, but it would still make sense if we want to be able to query bugs based on who interacted with them.

There is two type of participants that we might want to expose:
- participants: only users that wrote a comment or the initial bug
- actors: any user that interacted, including setting a label, changing the title ...

- [ ] add new functions on a Bug to compute both lists
- [ ] expose each lists in the Snapshot
- [ ] expose each lists in the GraphQL API
- [ ] add each list in the BugExcerpt
- [ ] implement new query selectors

**Comment by A-Hilaly** [comment]
Hello !

This is a good starting point for me, can i work on it ?

**Comment by MichaelMure** [comment]
Sure, go ahead ! Feel free to ask for clarifications as needed as well.

**Comment by A-Hilaly** [comment]
Thanks ! I'll open a PR as soon as i have something working !

**Comment by MichaelMure** [comment]
This has been dealt with by @A-Hilaly. @sandhose your turn ;)
