### ISSUE TITLE
Separate command (or option) to pull user identities from remote

### ISSUE THREAD

**Issue by mstenek** [MichaelMure/git-bug#1072]
In a freshly cloned repo, prior to interacting with any issues/bugs, git-bug forces you to create a brand new user -- even if your git-bug user is already stored in the remote; so, you end up having a different user every time you clone the repo!

Unless this is the desired functionality (which seems unnecessarily superfluous), **I suggest allowing git-bug to pull the users stored in the remote in a separate command (or option)** so that you can adopt your an already created user and from there interact with the issues/bugs. Thus potentially saving on a surfeit of duplicate (or orphaned) users.

**Comment by MichaelMure** [comment]
This is more of less a dup of #1003. The solution is not to have a new command, but to make `pull` fail later, only when we do need to have an identity (to merge data) instead of a hard requirement to do any pull. This would cover your scenario as you would pull data without having to do any merge (you don't have data locally yet, nothing to merge).

https://github.com/MichaelMure/git-bug/issues/1003#issuecomment-1411803779
