### ISSUE TITLE
git bug push fails with SHA-1 key message

### ISSUE THREAD

**Issue by dan-passaro** [MichaelMure/git-bug#1109]
I'm getting this error in git bug:

```
$ git bug push
Error: unknown error: ERROR: You're using an RSA key with SHA-1, which is no longer allowed. Please use a newer client or a different key type.
```

The keypair for my user account is SHA256, and is accepted by github (i.e. `git push` in the same repository works fine). Is there any way I can fix this?

**Comment by GlancingMind** [comment]
Hey thanks for reporting. :-)

Are you using the latest release of git-bug (v.0.8.0) or the master version?

Because go-git (which git-bug uses under the hood) had this issue, too. For Reference see: https://github.com/go-git/go-git/issues/516.

While go-git seems to already have merged a fix for this issue ([see this comment](https://github.com/go-git/go-git/issues/516#issuecomment-1455038678)), git-bug could still have this issue in its latest released version, because the fix was introduced shortly after the latest release of git-bug.

Date of latest git-bug release (v.0.8.0): Nov 20, 2022
Creation date of possible fix within go-git repo: Nov 25, 2022

But this is only a guess. ;-)

**Comment by dan-passaro** [comment]
Yes, I'm using the latest release. I'll try running from trunk instead. Thanks for the help!

**Comment by nicobo** [comment]
Hi.

I confirm building from the master fixes its. Why not making a new release ?

**Comment by sudoforge** [comment]
hey @nicobo, thanks for bringing this up. a new release will be made soon: https://github.com/MichaelMure/git-bug/milestone/9
