### ISSUE TITLE
Match gmail keybindings?

### ISSUE THREAD

**Issue by agentofuser** [MichaelMure/git-bug#229]
I accidentally opened and closed an issue a couple of times because the `o` key binds to "open" on Gmail. On the termui it binds separately to "push" on the list view and to "open/close issue" on the issue view.

Similarly, the `u` key binds to "up" on gmail (go back from thread view to list view), while on termui it's `q` (which exits the app when on list view, so easy to mistype).

Do you think this a change that would be useful?

**Comment by MichaelMure** [comment]
I quite like <kbd>Q</kbd> for `quit` and by extension `go back` (= quit the current screen).
For `push` and `pull` I used <kbd>I</kbd> and <kbd>O</kbd> because of input/output and because they are next to each other. I obviously couldn't use <kbd>P</kbd> for both.

I think what is going to change is `<kbd>O</kbd>` to open/close a bug. Eventually, more state will be added with most likely a sort of popup menu to select the state you want. It may be a good idea to keep <kbd>C</kbd> as a quick shortcut to close.

Does that make sense to you ?

**Comment by agentofuser** [comment]
Yeah, it would be impossible to have a set of keybindings that everyone was used to, so I defer to your judgement :) At some point it would be nice to have a way to customize them.
