### ISSUE TITLE
import error: issue creation: no matching operation found

### ISSUE THREAD

**Issue by kown7** [MichaelMure/git-bug#286]
Looks like bugs/issues created on the webpage cannot be imported.

```bash
$ git bug bridge pull
import error: issue creation: no matching operation found
imported 0 issues and 0 identities with default bridge
```

Versions should be latest `master`

**Comment by MichaelMure** [comment]
What bridge are you using ?

**Comment by kown7** [comment]
github

**Comment by MichaelMure** [comment]
Is the repo you are importing public ? Can you pinpoint what is not imported ?

**Comment by kown7** [comment]
The repo ist unfortunately private.

It seems to me, that the bridge can't import issues created with the Web-Interface.

**Comment by MichaelMure** [comment]
By "Web-Interface" you mean github.com, right ?

Also, do you have edited comment there ?

**Comment by kown7** [comment]
Yes - just like this issue.

I don't think I have any comments (maybe I've deleted one). I have certainly edited the issue at hand.

**Comment by MichaelMure** [comment]
The deleted comment might be the problem there. The error suggest that git-bug is looking for an imported comment to apply an edition on it but can't find it. I you can replicate that in a public repo that would certainly help.

**Comment by kown7** [comment]
I've deleted the non-imported issues/bugs but the problem remains.

**Comment by MichaelMure** [comment]
Hmm, I did a full import from a clean repo and everything seem to be there:

```
$ git bug bridge pull
new identity: 063fcf8593a4d4db2e92425e14bf395236099a2e
new issue: a300fbb6779b514514b7c8468d3fb11cf15046dd
updated comment: 19afc4cd78b8e58d65069749dd57c0aeaea9e9420ab25e47f3130ee0a5433e53
changed title: ba002752230b539d5f2c7b0383da7382de79c93657acb654d3948a62bdf44390
changed status: 0eedd6abcafaf6863e3960f05e3b91eadc4362cfbd729f08f5416e28b9bd711a
changed status: af791ed49869f95aa8c515953c34174a71cc498b4f60729dc5a0e369d12938a2
changed status: 74d13b40bef95e78ac3f45f54a529dbc816ee40c333c6420200903fa59d273c7
new comment: 656eed1ea4e0af610a87533795be85118a6d8cbc4cc394f142598c631f9a4c2a
changed status: 819042720fb479bc56934d4f9f6d47c18235be49e5214722a234ef68279ff240
new issue: 6bad8c57fd43bc2fa9b7de49421b220b89adbb39
updated comment: ddc1df0a554bea2da171340d88c90931af84f8c4f3af8421b0b4be4c3d54b4ea
updated comment: 56df334d40911bf0371823601694e4c058f4c09fbb926e8918666ca02d2a1b23
updated comment: c14b85a1660b831383b44229aa2584f94825315bff41edc136ad930c30e9d295
changed title: 1f183fa983f73354481ef651458069061aba4f1aad3866eaef53681b19936bae
new issue: b9a5888731bcf7d997fff634c55891d0ceab37df
updated comment: 5b665e200872121719a249d9421926250de9d7373a2cbbc27dad9416e0c6783f
new issue: bf639e7ac9c3ba6eef1acab499d0f63e95c1ba2d
updated comment: f189ad5383818aa9dc4a511bb691d27c108d7b9252289cd3dd385cb1fcfa9082
new issue: 085a68faad719992214de1a65ca55dd8a404d84a
imported 5 issues and 1 identities with default bridge
```

No errors

**Comment by MichaelMure** [comment]
Hey @kown7 I identified a place where your problem could lurk. Could you try the `github-import-error` branch and see if that solve it ?

**Comment by kown7** [comment]
I've made clean checkouts and the problem occurs if I start with `git bug pull` and then `git bug bridge pull`.

Calling these commands with inverted order solves the problem. ¯\_(ツ)_/¯

**Comment by MichaelMure** [comment]
I looked in more details into this and I think what happened is that you used the bridge multiple times from different repository and pushed the bugs (not with a bridge, the normal push) to the git remote. When you push like this, git-bug doesn't know that it is pushing duplicates (they have different ID).

Later when you do a `git bug pull` you pull again the same duplicates.

The problem is that you then end up with multiple bugs associated with the same Github issue and the bridge get confused.

While this is not an actual problem in git-bug, the `github-import-error` made that easier to see and understand.

Now what you need to do is to delete all those pushed bugs (see https://github.com/MichaelMure/git-bug/blob/master/Makefile#L46-L47) and everything should be back to normal.

**Comment by kown7** [comment]
Thank you for the input.

So basically mixing `git bug` remotes and `git bug bridge` remotes isn't a good idea? Maybe there should be warning against this use.

**Comment by MichaelMure** [comment]
Mixing those can be a very valid use case if:
- there is a single instance importing (otherwise, another instance might be out of date and import something that has already be imported on another one and you get a conflict)
- you don't clear your repo, bridge import then pull from the remote the previously imported bugs (it's essentially the same scenario: two instances importing without knowing each other data)

True, a warning would be useful
