### ISSUE TITLE
WebUI returns 404.

### ISSUE THREAD

**Issue by sarg** [MichaelMure/git-bug#33]
I have installed git-bug with `go get github.com/MichaelMure/git-bug`.
When I run `git bug webui` it starts web-server but returns 404 for index.html.
GraphQL API and Playground are working fine.

Precompiled binary from github releases isn't affected with this problem.

```
❯ git bug --version
git-bug version 0.2.0

❯ ~/Downloads/git-bug_linux_amd64 --version
git-bug version 0.2.0
```

**Comment by MichaelMure** [comment]
I see the problem.

What happen is that it requires the build tag `deploy_build` (see the Makefile) to use the pre-packaged webui. If this tag is not present, it fetch the webui from the project. As you have not installed the npm package and built it, you get nothing.

This logic should be inverted because it indeed breaks the go get process.
