### ISSUE TITLE
termui hanging in FreeBSD

### ISSUE THREAD

**Issue by njthomas** [MichaelMure/git-bug#387]
When I start termui, I see the git-bug termui interface, but none of my keys work. I have to kill the process to get out.

- this is only happening on FreeBSD
- it is happening FreeBSD 11.3 and 12.1 (I've not tested with 12.0)
- it is not happening on OpenBSD (tested on 6.6)
- in FreeBSD, I used both the ports/pkg version (v0.7.1), but I also compiled v0.7.1, and v0.70 from src
- it does not seem to be SHELL dependent (it happens in both zsh and bash)
- I have built v0.5.0 from src and the problem does not happen there
- I believe I first saw the problem on or about 2019-09-18 because of this comment: https://github.com/MichaelMure/git-bug/issues/99#issuecomment-532893529 (I did not have time then to investigate further)
- will try and investigate further, in the meantime, I'm asking other FreeBSD users to try and replicate

FWIW, all other git-bug operations seem to work (add, ls, ls-label, etc.)

**Comment by bsdlcook** [comment]
FreeBSD port maintainer for git-bug here.

As the go package [awesome-gocui](https://github.com/awesome-gocui/gocui) is using a custom fork of termbox, it's slightly outdated and hasn't inherited the FreeBSD [fixes from upstream](https://github.com/nsf/termbox-go/commit/58d4fcbce2a7e6a3a48afbc6b7ec2a916ac33ee0) and subsequently causing these issues you're experiencing. Since applying the patch aforementioned I'm no longer facing this issue, either:

* Fixes are merged into the forked termbox awecome-gocui uses;
* awesome-gocui switches it's custom fork to the upstream version.

In any case it would be worth creating an [issue there](https://github.com/awesome-gocui/termbox-go) mentioning this. For now, I'll submit a patch on FreeBSD bugzilla including the fixes and we can go from there.

**Comment by MichaelMure** [comment]
> FreeBSD port maintainer for git-bug here.

Ho hello, thank you !

So if this patch is accepted in the FreeBSD package, does that mean that this problem is resolved *in practice* ? Otherwise there is still the possibility to fork the forked (*sight*) go-termbox and pin this version in git-bug but that's something I would gladly avoid if possible.

**Comment by bsdlcook** [comment]
> So if this patch is accepted in the FreeBSD package, does that mean that this problem is resolved in practice ?

In theory, it's resolved in practice via the package; only because a band-aid is being applied to this very particular case—what it doesn't do is solve the underlying issue. It doesn't stop someone from manually cloning this repo on FreeBSD, building and facing what's been described above. Since it's a one-liner fix it wouldn't be too difficult to have it merged into the fork at [awesome-gocui/termbox-go](https://github.com/awesome-gocui/termbox-go). However, I'm not sure if/when it'll be merged seeing that it hasn't had that much activity.

I suggest:

1.  Creating a pull-request on [awesome-gocui/termbox-go](https://github.com/awesome-gocui/termbox-go) addressing the [upstream fix](https://github.com/nsf/termbox-go/commit/58d4fcbce2a7e6a3a48afbc6b7ec2a916ac33ee0);
2. Mentioning that you can install the package on FreeBSD (``pkg install git-bug``);
3. Pinning this issue so FreeBSD users can find this thread.

I'll happily complete both _1_ and _2_. I don't mind either way, really. :)

**Comment by MichaelMure** [comment]
Yes the best scenario is to have that merged upstream. Not sure it's going to happen soon because they are in the process of ditching entirely go-termbox to use tcell instead (https://github.com/awesome-gocui/gocui/pull/45). This is a rather slow and painful process.

1 and 2 sounds good to me. Let's keep this issue open as well until it's fully resolved.

**Comment by bsdlcook** [comment]
In other news, the FreeBSD bugzilla report has been reviewed and [merged](https://svnweb.freebsd.org/ports?view=revision&revision=535333) fixing this issue for the package.

> Not sure it's going to happen soon because they are in the process of ditching entirely go-termbox to use tcell instead

For now I think it's best to wait and see what happens in regards to this, then to act accordingly for termbox.

**Comment by njthomas** [comment]
Confirmed that the patch fixes the FreeBSD port version, and I was able to apply the same patch and build git-bug from GitHub source.

**Comment by MichaelMure** [comment]
This should be resolved now as gocui doesn't use termbox anymore.
