### ISSUE TITLE
[WebUI] Read-only mode for serving publicly

### ISSUE THREAD

**Issue by tazjin** [MichaelMure/git-bug#402]
Hey, and thanks for git-bug, it is an amazing idea!

We've started using git bug for our community monorepo at [code.tvl.fyi](https://code.tvl.fyi) and would like to be able to host a read-only web UI so that we can link to bugs etc., without people needing to pull them locally.

It seems that the web UI currently expects to be launched with an identity, and that it always provides features such as a comment field. Have you considered adding a read-only mode which could be used for serving it publicly? Alternatively, would patches for supporting this be welcome?

Thanks!

**Comment by MichaelMure** [comment]
Yes this would make sense.

At the moment, the WebUI implicitly use the default User of the git repo it's launched from as the active user in the WebUI. The plan is to have it eventually accept external authentication (OAuth typically) so that people without git commit access can participate on the bugtracker.

But having this implies that there is sometimes no logged user and the WebUI should be read-only at that point. Ideally this read-only feature is framed that way: not as a special hardcoded mode, but as a fallback when there is no logged user. It would then be just a matter of adding a new `--read-only` flag to the `webui` command to run the GraphQL API without a user.

This has some implication in the GraphQL API though: even if `Repository.userIdentity` in the GraphQL API can be null, there is still the assumption in some places (typically the mutations) that a user always exist. 

I very much welcome patches to do that.
