### ISSUE TITLE
[github] Can't use two bridges at the same time

### ISSUE THREAD

**Issue by cript0nauta** [MichaelMure/git-bug#419]
Hi! I've been using git-bug for a while and had and awesome experience with it,
except for a small annoying bug: i configured a bridge to my private GitHub
repo and exported the issues, then I deleted that repo and tried to re-export
the issues to a new repo without success.

Steps to reproduce:

* Setup a GtiHub bridge `br1`
* Run `git bug bridge push br1`. It will create the issues successfully
* Setup a second GitHub bridge `br2`. This one should use a GitHub repo different than `br1`'s
* Run `git bug bridge push br2`. It will say `exported 0 issues with br2 bridge` and won't export
  anything into the second repo

As a workaround, I was able to make `git bug bridge push br2` export the issues
by changing the name of the GitHub metadata keys:

```diff
diff --git a/bridge/github/github.go b/bridge/github/github.go
index 1e85eb9..14448d3 100644
--- a/bridge/github/github.go
+++ b/bridge/github/github.go
@@ -15,8 +15,8 @@ import (
 const (
 	target = "github"
 
-	metaKeyGithubId    = "github-id"
-	metaKeyGithubUrl   = "github-url"
+	metaKeyGithubId    = "github-id-2"
+	metaKeyGithubUrl   = "github-url-2"
 	metaKeyGithubLogin = "github-login"
 
 	confKeyOwner        = "owner"
```

With this change, git-bug won't mark the existing issues as already exported.

One possible solution to this problem would be to make the GitHub metadata keys
keyed with the bridge name, so a bug can be marked as exported in just one
GitHub bridge instead of in all of them.

I don't need this issue to be fixed since my plan was to use git-bug only until
I release my tool, and then move to GitHub issues. Using the workaround
described above was enough for me. But I wanted to create the issue to prevent
others from having this same problem.

**Comment by MichaelMure** [comment]
As you may have guessed, this is intentional, at least for now.

As a starting point, the github bridge can only push edits that it has an API token for. You can load more than one token, but you need to have them to begin with. Generally speaking, git-bug is a pretty bad issue transfer tool (for now).

Now, if you configure two bridges, what's the behavior that you expect ? You could expect that bugs are pushed/pulled from both as you did (that is, pretty much a transfer tool), or you could expect that they stay segregated because you just want to centralize multiple source in a single local repo. In this latter case if git-bug fail to segregate bugs you are in a world of pain.

Because git-bug is a pretty bad transfer tool, I chose to segregate bugs to avoid problem for the common use case. In the future this could be relaxed *if* there is a way to control the behavior, with the segregation still being the default.
