### ISSUE TITLE
A bug/issue created before import is oldest in order even though it has most recent date

### ISSUE THREAD

**Issue by theWebalyst** [MichaelMure/git-bug#470]
While trying git-bug out I did the following:
- installed the 0.7.1 binary
- checked out the different UIs
- created a local test repo by cloning https://github.com/github-tools/github
- in that repo, used `git-bug add` to create a new bug report/issue
- imported the >600 issues from https://github.com/github-tools/github
- listed the issues using the git-bug CLI and webui and in both cases the newest (locally create issue) appears last, after all the imported issues.

OS: Ubuntu 20.04
git-bug release build: 0.7.1 (amd 64)

I know git-bug can't just rely on the dates, so am not sure if this is expected behaviour. If so perhaps it can be documented in relevant places.

BTW: I'm very impressed with my brief experiments so far and will continue to look at using git-bug in my attempt to build a decentralised (p2p) alternative to the existing github style experience. If it looks promising I'll open an issue about that. I posted briefly in the gitter about it this week, but have not seen a response there yet.

If any git-bug users or contributors are present on mastodon or twitter please let me know as I would like to follow you.

**Comment by MichaelMure** [comment]
It does look a little odd in this scenario but it actually make sense because bugs get ordered by time of creation *in git-bug* (either on your repo or a remote one, but github is not part of that). When you imported from github, you created new bugs *after* the first one.

I'm all for improving the documentation but I'm not sure how to document those kind of small oddities without flooding the important message in details. I'm open to suggestions.

> I posted briefly in the gitter about it this week, but have not seen a response there yet.

Sorry about that :-| Gitter is a little weird and it happen often that I just don't get any notifications.

Closing as it's not an actual bug.
