### ISSUE TITLE
Rename git-bug => git-issue

### ISSUE THREAD

**Issue by MartinDelille** [MichaelMure/git-bug#73]
What do you think of renaming the project to *git-issue*?

I find the name *issue* is more descriptive of what we do on software project based on git and this is the current convention used by gitllab and github.

I know that *bug* is shorter that *issue* bug we could use alias.

**Comment by neithernut** [comment]
There is [already](https://github.com/yuroyoro/git-issue) [taken](https://github.com/dspinellis/git-issue). And so is [git-issues](https://github.com/duplys/git-issues).

**Comment by MartinDelille** [comment]
Is it a problem? Both projects are not maintained anymore and yours has support from git core developer (they talk to me about it on the dev mailing list).

**Comment by MartinDelille** [comment]
Ok feel free to close this issue if this is not appropriate. My point was just to propose a more adapted name in my opinion. I indeed put wrong word in the git core developer mouth and I apologize for that! 😉

**Comment by rafasc** [comment]
@MartinDelille I wasn't saying this issue isn't appropriate. Developers did *suggest* renaming this project to something less prone to being used in the future as a default command. 

But It's hard to come up with a sensible choice as some of the obvious choices are taken.

So unless there's a better candidate, let's assume the author did the conscious decision to keep it things as it is. 🙂

**Comment by MichaelMure** [comment]
I didn't realize I haven't answered here, sorry about that.

There is two different problem here:

Naming the project `git-bug` instead of `git-issue` or something else: naming is hard and the obvious `git-issue` was already taken. I didn't want to conflict with that so I went with `git-bug` that was unused and not that bad.

Namespace grab in git command: some git developers complained about the namespace grab because they might want to make a bug command in the future. It also conflict with a command from the git-extra package. I'm considering dropping out of the git porcelain framework and renaming the binary `gb` or something else. No more conflict or namespace grab, and shorter commands. I haven't made my mind about that yet though.

**Comment by xaur** [comment]
I see no problem with multiple projects named `git-issue`. It's only problematic when a user tries to install and use more than one simultaneously. As other commenter [noted](https://github.com/MichaelMure/git-bug/issues/73#issuecomment-437861831), there are already two such projects.
