### ISSUE TITLE
git bug push not working

### ISSUE THREAD

**Issue by mnaderhirn** [MichaelMure/git-bug#742]
when I try to push my issues i get the following error
![grafik](https://user-images.githubusercontent.com/62671479/153078591-d7f3f372-6977-441d-9abf-c10abd393096.png)
Do I have a wrong configuration?

**Comment by mnaderhirn** [comment]
Short update - push is working just getting the messages above, so it is just a minor issue

**Comment by smoyer64** [comment]
@mnaderhirn - Can you provide a bit of information about your OS and about your remote repository.  Also, please post the output of the following command:

```
git config --list | grep credential
```

This (non-error?) message appears to be from the remote repository and reports of this "extra output" appear to be related to the `credential-manager-core` project's rename (https://github.blog/2022-04-07-git-credential-manager-authentication-for-everyone/).  In some reports, the following command fixes the problem (though I'm not sure why authentication continues to work afterwards):

```
git config --global --unset credential.helper
```

Note that it's also possible that this setting is in the repository's configuration - `<repo>/.git/config`.  Does this message also get displayed when you simply run `git push` instead of `git bug push`?

**Comment by MichaelMure** [comment]
Closing as we don't have more information. Please reopen if needed.
