### ISSUE TITLE
QUEST: gitlab bridge fails to pull "Error: missing identity token"

### ISSUE THREAD

**Issue by stacyharper** [MichaelMure/git-bug#927]
Hey there,

 tried;

```sh
git bug user create
….
git bug bridge auth
…
git bug bridge pull
Error: missing identity token
```

Have I missed something ?

Thanks for the help !

**Comment by MichaelMure** [comment]
If you have used git-bug before, you might need to run https://github.com/MichaelMure/git-bug-migration

Otherwise, it seems like the bridge doesn't find your credentials anymore. I don't know how you ended up in that situation (might be a bug, might be due to the migration needed, might be because you used a development version). I think you should be able to resolve that by removing the bridge (`git bug bridge rm`) and doing the `configure` again.

**Comment by stacyharper** [comment]
I made it to works. I think my problems was that I used my email address instead of my shoft login while configuring the bridge
